# Generated by Django 3.2.2 on 2021-05-13 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_resposta_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='corpo',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='questao',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='resposta',
            old_name='corpo',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='resposta',
            old_name='questao',
            new_name='question',
        ),
    ]
