# Generated by Django 3.2.2 on 2021-05-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210526_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='area',
            field=models.CharField(choices=[['Matemática', 'Matemática'], ['Hardware', 'Hardware'], ['Software', 'Software'], ['Inteligência Artificial', 'Inteligência Artificial'], ['Lógica', 'Lógica'], ['Programação', 'Programação'], ['Física', 'Física'], ['Química', 'Química'], ['Ciclo Básico', 'Ciclo Básico']], default='Ciclo Básico', max_length=200),
        ),
    ]
