# Generated by Django 3.2.2 on 2021-06-01 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_questao_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main.questao'),
        ),
    ]
