# Generated by Django 3.2.2 on 2021-06-04 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='author',
        ),
    ]
